---

- name: "wait for FRAM to come up"
  uri:
    url: "{{ amster_fram_install_serverUrl }}/config/options.htm"
    status_code: 200
    return_content: "no"
  register: result
  until: result.status == 200
  retries: 1
  delay: 1

- name: create FRAM installation file
  become: true
  become_user: "{{ amster_fr_user }}"
  template:
    src: "installfram.amster.j2"
    dest: "/tmp/installfram.amster"

- name: create ForgeRock Access Manager Configuration Directory
  file:
    path: "{{ amster_fram_install_cfgDir }}"
    state: "directory"
    owner: "{{ amster_fr_user }}"
    mode: 0700

- name: execute FRAM installation
  become: true
  become_user: "{{ amster_fr_user }}"
  shell: "{{ amster_install_directory_base }}/amster /tmp/installfram.amster"
  args:
    executable: /bin/bash